### ISSUE TITLE
Shouldn't bower be project specific?

### ISSUE THREAD

**Issue by jacobtomlinson** [met-office-lab/our-bower.json#1]
I hope I'm not missing the point but I was under the impression that a bower.json file would be project specific and not system specific.

So you include it in the repository for a specific project to allow contributors to get set up with the correct thing.

Just as an example if we create two projects which use different versions of jQuery you would want a separate bower.json for each.

Similar to having a requirements.txt file in a Python module for pip.

**Comment by niallrobinson** [comment]
from reading a bit more, I think you might be right. I'm not sure I see the point thought. Its just as easy to copy in all the dependencies yourself.

**Comment by tpowellmeto** [comment]
Hi guys,

I have only limited experience doing front end dev but from what I understand Jacob you are correct that you would want a separate bower.json file per app. 

As I understand it bower is a/the dependency management tool for js.
If you're trying to set up a descent dev environment you could look at gulp or grunt, the latter being the tool that the webapps guys in TIS currently favour. These are essentially task runners that can build and serve your app.

Recently i have also heard good things about a tool called yeoman which as I understand incorporates all/most of the above and is kind of a configuration tool to get you up and running with some boilerplate stuff. 

Hope this helps,

Tom

**Comment by jacobtomlinson** [comment]
I would presonally say my main reasons to use bower are 

> No need to commit dependencies to version control
> No need to locate various builds (debug, minified, etc)

More reasons here
http://programmers.stackexchange.com/questions/224828/why-should-i-use-bower

**Comment by niallrobinson** [comment]
that doesn't seem like a compelling enough case at this stage. You can commit dependencies to version control by commiting them to version control, and you can local builds in 20s by googling them. I'll remove the repo anyway as it just clutters up the page
